### ISSUE TITLE
Set tag/branch version of a module

### ISSUE THREAD

**Issue by manuelver** [activa-prefapp/documentation#20]
How to set a git repository tag/branch when adding a module 

[Example of aws rds module](https://github.com/kubevela/catalog/blob/7a137bd11b46a09883215648d3e05ad2069bd00b/addons/terraform-aws/definitions/terraform-aws-rds.yaml#L14)

**Comment by davma-io** [comment]
It will be necessary to wait for the release of a new version of KubeVela to see the new features implemented in:

#https://github.com/kubevela/kubevela/pull/6363
